AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation for The Daily Blend

Parameters:
  LambdaFunctionS3Bucket:
    Type: String
  LambdaFunctionS3Key:
    Type: String

Resources:
  FeedProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DailyBlendFeedProcessor
      Runtime: python3.8
      Handler: feed_processor.lambda_handler
      Code:
        S3Bucket: !Ref LambdaFunctionS3Bucket
        S3Key: !Ref LambdaFunctionS3Key
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DB_SECRET: !Ref PlanetScaleDBSecret

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSecretsManagerExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref PlanetScaleDBSecret

Outputs:
  LambdaFunctionName:
    Description: "The name of the Lambda function"
    Value: !Ref FeedProcessorLambda
