version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily_blend_web
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: mysql:8
    container_name: daily_blend_db
    env_file: .env

  redis:
    image: redis:latest
    container_name: daily_blend_redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_celery_worker
    depends_on:
      - db
      - redis
    env_file: .env
    command: celery -A project worker --loglevel=info

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_celery_beat
    depends_on:
      - db
      - redis
    env_file: .env
    command: celery -A project beat --loglevel=info
